# Generated by Django 5.1.1 on 2024-12-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='bio',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
