# Generated by Django 5.1.1 on 2024-12-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_bio_products_description_remove_offer_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
