# Generated by Django 5.1.1 on 2024-12-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='bio',
        ),
    ]
